export const NUM_DEFAULT_TICKET_IN_LIST = 6

export const NUM_CELLS_FIRST_FIELD = 20
export const NUM_CELLS_SECOND_FIELD = 4

export const NUM_SELECTED_CELLS_FIRST_FIELD = 8
export const NUM_SELECTED_CELLS_SECOND_FIELD = 1

export const NUM_ADD_TICKETS = 2

export const NUM_MIN_FILL_TICKETS = 1
export const NUM_MAX_FILL_TICKETS = 10

export const NUM_LAST_FEW_EDITIONS = 10
